//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JereckNET.LicenseManager.Sample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JereckNET.LicenseManager.Sample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LicensePublicCertificateCRT {
            get {
                object obj = ResourceManager.GetObject("LicensePublicCertificateCRT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;2zKqTYqYTHjT/3S7yIQxaA42/M+GFkvEH2VJSs2Ybv70l07gvbkCk3OmJfYnLGJCWbPOxX3rsc7GhwVEuY9QAOqvmHGcJi28GLFUiiDqgr21DD3p4U/PSopygqFcMv61KO3T5SVpEpRP8N2n4/H4HRD5cBqFz21g913mmldrHFpin0AyesYx6XI5IY49hQkgdpRyx6rQoBi5DFSKAGSNYpoV2r90RZZ8kMEce8+FbSCQ+7W6C270QENOUveyjK6k+Khrp5KYKTZVhQvyDWScmsa5VBhecumWtCvIiiOXoJP1xlqbHOse/iQJh2V9OwXLVu6TKrzLDujzIBlpb25EZVLtcs9aLiGBPG5hrLehqGV3xfjbIt+VaXBz4sY9i7J3tFoa2RnYvM0QtPBHI1YrJxDc9igcV0qjVWWfICmNU9moYKkjvamYlZJYOnEAbOsDHwnoAqXgPsFf/hEme99ATPEisoK7AM+R5MOsZh/Mf6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicensePublicKey {
            get {
                return ResourceManager.GetString("LicensePublicKey", resourceCulture);
            }
        }
    }
}
